server:
  port: 9191

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: DEPARTMENT
          uri: lb://DEPARTMENT
          predicates:
            - Path=/department/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost


